name: image_segmentation
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.6.0=py312hca03da5_1
  - aom=3.12.1=ha237518_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - backports.zstd=1.1.0=py312hb3cf4b8_0
  - blas=1.0=openblas
  - bleach=6.3.0=pyhcf101f3_1
  - brotli-python=1.2.0=py312h5b255a4_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.2.1=py312hca03da5_1
  - contourpy=1.3.3=py312h20e30b6_0
  - cycler=0.12.1=py312hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - eval_type_backport=0.3.1=pyha770c72_0
  - expat=2.7.4=h50f4ffc_0
  - filelock=3.20.3=py312hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.61.0=py312haa24f5a_0
  - freetype=2.14.1=h7cdc921_0
  - fribidi=1.0.16=h8859324_0
  - fsspec=2026.1.0=py312h7eb115d_0
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - gitdb=4.0.12=py312hca03da5_0
  - gitpython=3.1.46=py312hca03da5_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.2=py312hbcc4bda_0
  - graphite2=1.3.14=hc377ac9_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h9837a22_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h313beb8_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=py312hca03da5_0
  - jinja2=3.1.6=py312hca03da5_0
  - jpeg=9f=h2f69dba_0
  - kaggle=1.8.4=pyhcf101f3_0
  - kagglesdk=0.1.15=pyhcf101f3_0
  - kiwisolver=1.4.9=py312haeee614_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libavif=1.3.0=h839b4eb_0
  - libcxx=21.1.8=hb4ce287_0
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.2.0=h09d7db9_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.86.3=hcacd345_0
  - libiconv=1.16=h80987f9_3
  - libopenblas=0.3.31=h7813bb4_0
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.54=h5c318fc_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libsqlite=3.51.2=h1b79a29_0
  - libtiff=4.7.1=h367c460_0
  - libtorch=2.5.1=gpu_mps_h7b1bc93_204
  - libuv=1.48.0=h80987f9_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxcb=1.17.0=h3fc13f7_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.8=hfab7639_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py312h80987f9_0
  - matplotlib=3.10.8=py312hca03da5_0
  - matplotlib-base=3.10.8=py312haa222d5_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py312hca03da5_0
  - ncurses=6.5=hee39554_0
  - networkx=3.6.1=py312hca03da5_0
  - nomkl=3.0=0
  - numpy=2.4.2=py312h4bb6f22_0
  - numpy-base=2.4.2=py312h23175f9_0
  - openssl=3.6.1=hd24854e_1
  - opentelemetry-api=1.38.0=py312hca03da5_0
  - packaging=25.0=py312hca03da5_1
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.1.0=py312h7b5562e_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=py312hca03da5_0
  - protobuf=5.29.3=py312h514c7bf_0
  - psutil=7.0.0=py312haa24f5a_1
  - pthread-stubs=0.3=h1a28f6b_1
  - pydantic=2.12.4=py312hca03da5_0
  - pydantic-core=2.41.5=py312h931abed_1
  - pyparsing=3.2.5=py312hca03da5_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.8=h89a136b_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python_abi=3.12=3_cp312
  - pytorch=2.5.1=gpu_mps_py312hbd1d365_204
  - pyyaml=6.0.3=py312h091b9d3_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=pyhcf101f3_1
  - sentry-sdk=2.45.0=py312hca03da5_0
  - setproctitle=1.3.7=py312haa24f5a_0
  - setuptools=80.10.2=py312hca03da5_0
  - six=1.17.0=py312hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - smmap=5.0.2=py312hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - sympy=1.14.0=py312hca03da5_1
  - text-unidecode=1.3=pyhd8ed1ab_2
  - tk=8.6.15=hcd8a7d5_0
  - torchvision=0.20.1=mps_py312h620d032_102
  - tornado=6.5.4=py312haa24f5a_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - typing=3.10.0.0=py312hca03da5_0
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing-inspection=0.4.2=py312hca03da5_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wandb=0.25.0=py312h232e7c1_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.46.3=py312hca03da5_0
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zipp=3.23.0=py312hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/miniconda3/envs/image_segmentation
