name: image_segmentation
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - torchvision
  - pytorch
  - matplotlib
  - kaggle
  - wandb
prefix: /opt/miniconda3/envs/image_segmentation
